const strings = {
    onBoarding: {
        dashboard: 'Dashboard',
        profile_dashboard: 'Profile Dashboard',
        add_department: 'Add Department',
        add_tpo: 'Add TPO',
        add_student: 'Add Student',
        add_new_activity: 'Add New',
        activity: 'Activity',
        tpo_staff: 'TPO Staff',
        students: 'Students',
        do_you_want_delete: 'Do you want to delete !',
        tpo_staff: 'TPO Staff',
        campus_student: 'Campus Student',
        suspend_tpo_staff: 'Suspended TPO Staff',
        suspend_campus_student: 'Suspended Student',
        edit_profile: 'Edit Profile',
        change_password: 'Change Password',
        set_mpin: 'Set MPIN',
        high_security_password: 'High Security Password'
    },
    footer: {
        powered_by: 'Powered by Medicaps University',
    },
    users: {
        student: 'Students',
        tpo: 'TPO',
        admin: 'Admin',
        welcome: 'Welcome',
        welcome_admin: 'Welcome Admin',
        welcome_tpo: 'Welcome TPO',
        welcome_student: 'Welcome Student',
        welcome_signup: 'Signup to continue!',
        already_account: 'Already have an account, ',
    },
    textInput: {
        first_name: 'First Name',
        last_name: 'Last Name',
        email: 'Email ID',
        password: 'Password',
        confirm_password: 'Confirm Passwword',
        contact: 'Mobile Number',
        enrollment: 'Enrollment ID',
        department: 'Department/Branch',
        old_password: 'Old Password',
        new_password: 'New Password',
        security_password: 'Security Password',
    },
    buttons: {
        create_account: 'Create Account',
        login: 'LOGIN',
        signup: 'SIGNUP',
        signup_page: 'Don\'t have an account? Create one new',
        login_page: 'Login!',
        cancel: 'Cancel',
        delete: 'Delete',
        suspend: 'Suspend',
        activate: 'Activate',
        update_profile: 'Update Profile',
        set_mpin: 'Set MPIN',
        change_password: 'Change Password',
        update_password: 'Update Password',
        set_security_code: 'Manage High Security Password',
        terms_condition: 'Terms & Conditions.'
    }
}
export default strings;